include:
  - path: ../docker_global_config.umbra.yaml
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ~/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - homepage.group=Automation
      - homepage.name=HomeAssistant
      - homepage.icon=home-assistant.png
      - homepage.href=http://assistant.umbra.com
