include:
  - ../docker_global_config.umbra.yaml
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ~/vw-data:/data
      - /etc/ssl:/ssl:ro
    ports:
      - "8081:80"
    environment:
      - ROCKET_TLS:'{certs="/ssl/certs/umbra.com.cert.pem",key="/ssl/private/umbra.com.key.pem"}'
      - ROCKET_PORT=80
      - DOMAIN=http://vault.umbra.com:8081
      - SIGNUPS_ALLOWED=true  
    labels:
      - homepage.group=Administration
      - homepage.name=VaultWarden Password Manager
      - homepage.icon=vaultwarden.png
      - homepage.href=http://vault.umbra.com
